GET http://localhost:3000/api/categorias

###

GET http://localhost:3000/api/categorias/15
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiZ3ZlcmFAdXYubXgiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJHdWlsbGVybW8gSHVtYmVydG8gVmVyYSBBbWFybyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmFkb3IiLCJleHAiOjE3MTg3ODE0MTgsImlzcyI6IlNlcnZpZG9yRmVpSldUIiwiYXVkIjoiQ2xpZW50ZXNGZWlKV1QifQ.zim6uxkKG1Gmr8oNM_hsV-Ed8i6M8kry20D8zcUpolc

###

POST http://localhost:3000/api/categorias
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiZ3ZlcmFAdXYubXgiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJHdWlsbGVybW8gSHVtYmVydG8gVmVyYSBBbWFybyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmFkb3IiLCJleHAiOjE3MTg3ODE0MTgsImlzcyI6IlNlcnZpZG9yRmVpSldUIiwiYXVkIjoiQ2xpZW50ZXNGZWlKV1QifQ.zim6uxkKG1Gmr8oNM_hsV-Ed8i6M8kry20D8zcUpolc

{
    "nombre": "Categoria de prueba"
}

###

PUT http://localhost:3000/api/categorias/16
Content-Type: application/application/json

{
    "categoriaid": 16,
    "nombre": "Categoria de prueba editada"
}

###

DELETE http://localhost:3000/api/categorias/16
